# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: pgmann-public
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn --batch-mode package javadoc:javadoc --file pom.xml
    - name: Archive final plugin JAR
      uses: actions/upload-artifact@v2
      with:
        name: CommandPrompt JAR
        path: target/CommandPrompt-*-SNAPSHOT.jar
    - name: Publish JAR to Maven Repo
      if: ${{ github.event_name == 'push' }}
      run: mvn --batch-mode deploy --file pom.xml
      env:
        MAVEN_USERNAME: pgmann
        MAVEN_PASSWORD: ${{ secrets.MVN_UPLOAD_PASSWORD }}
